variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

services: 
  - docker:dind

stages:
  - maven-build
  - docker-build
  
maven-build:
  stage: maven-build
  image: maven:3.3.9-jdk-8
  artifacts:
   paths:
     - rest-server/target/
  script:
    - cd dreamteam-pom
    - mvn $MAVEN_CLI_OPTS clean install
    - cd ../rest-server
    - mvn $MAVEN_CLI_OPTS clean package
    
docker-build:
  stage: docker-build
  image: docker:stable
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd rest-server
    - docker build -t $CI_REGISTRY_USER/dreamteam-rest .
    - docker push $CI_REGISTRY_USER/dreamteam-rest