apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
  - image: bobrohan/dreamteam-web:latest
    name: frontend
    ports:
    - containerPort: 8089
    resources:
      limits:
        cpu: 500m
        memory: "209715200"
  restartPolicy: OnFailure
status: {}
